# Generated by Django 3.2.9 on 2021-11-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField()),
                ('aurhor', models.CharField(default='', max_length=100)),
                ('page', models.IntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
