# Generated by Django 3.2.9 on 2021-11-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20211129_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
