# Generated by Django 3.2.9 on 2021-11-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='immage',
        ),
    ]
